// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies promising online business opportunities with minimal manual input, assessing market gaps and emerging trends to pinpoint ventures with high potential.
 *
 * - identifyPromisingOpportunities - A function that identifies promising online business opportunities.
 * - IdentifyPromisingOpportunitiesInput - The input type for the identifyPromisingOpportunities function.
 * - IdentifyPromisingOpportunitiesOutput - The return type for the identifyPromisingOpportunities function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyPromisingOpportunitiesInputSchema = z.object({
  marketTrends: z
    .string()
    .describe('Description of current market trends and emerging technologies.'),
  userInterests: z
    .string()
    .describe('Description of the user interests and skills.'),
});
export type IdentifyPromisingOpportunitiesInput =
  z.infer<typeof IdentifyPromisingOpportunitiesInputSchema>;

const OpportunitySchema = z.object({
  opportunityName: z
    .string()
    .describe('Name of the business opportunity.'),
  description: z.string().describe('A short description of the business.'),
  potential: z
    .string()
    .describe('An assessment of the opportunities potential, considering financial upside and market size.'),
  risk: z
    .string()
    .describe('An assessment of the risks involved, including market, execution, and financial risks.'),
  quickReturn: z
    .string()
    .describe('An assessment of how quickly a return on investment can be expected (e.g., Short, Medium, Long term).'),
  priority: z
    .string()
    .describe(
      'A priority score, from 1-10, of which opportunity to pursue first. This should be a synthesis of potential, risk, and quick return.'
    ),
});

const IdentifyPromisingOpportunitiesOutputSchema = z.array(
  OpportunitySchema
);
export type IdentifyPromisingOpportunitiesOutput =
  z.infer<typeof IdentifyPromisingOpportunitiesOutputSchema>;

export async function identifyPromisingOpportunities(
  input: IdentifyPromisingOpportunitiesInput
): Promise<IdentifyPromisingOpportunitiesOutput> {
  return identifyPromisingOpportunitiesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyPromisingOpportunitiesPrompt',
  input: {schema: IdentifyPromisingOpportunitiesInputSchema},
  output: {schema: IdentifyPromisingOpportunitiesOutputSchema},
  prompt: `You are an AI assistant designed to identify promising online business opportunities based on a matrix of highest potential, low risk, and quick return.

Analyze the provided market trends and user interests to pinpoint ventures with high potential. For each opportunity, evaluate its potential, risk, and the expected time to see a return.

Market Trends: {{{marketTrends}}}
User Interests: {{{userInterests}}}

**Business Model Considerations:**
When brainstorming, consider unmet needs in the SaaS market. Think about "pain-killer" solutions for niche problems.
Structure your suggestions around modern business models:
- Packed, service-based solutions.
- Subscription tiers for product packages (including free tiers and membership discounts).
- Corporate branding and marketing from the outset.
- A strong web presence with pre-built, value-adding automation services.

**Project Development Framework:**
For promising ventures like "AI Workflow Automation & Prompt Engineering Specialist," frame the output as a project brief.
This brief should align with a phased project management approach:
1.  **Initiation**: Define boundaries, assemble the PMO team, configure reporting.
2.  **Execution & Control**: Operate within defined tolerances, manage the project.
3.  **Closure & Growth**: Capture lessons learned for CI/CD, transition to a sustainable lifecycle, and manage growth.
Success is measured by governance, market dominance, quality delivery, financial gains, and commercial achievements (customer satisfaction, brand loyalty).

Consider various online business models, including but not limited to: side-hustles, passive income generators, freelance performance portals, dropshipping e-commerce traders, and social media management.

The final priority score should be a synthesis of these factors: high potential, low risk, and quick return should result in a higher priority.

Return the opportunities as a JSON array.
`,
});

const identifyPromisingOpportunitiesFlow = ai.defineFlow(
  {
    name: 'identifyPromisingOpportunitiesFlow',
    inputSchema: IdentifyPromisingOpportunitiesInputSchema,
    outputSchema: IdentifyPromisingOpportunitiesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
