// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies promising online business opportunities with minimal manual input, assessing market gaps and emerging trends to pinpoint ventures with high potential.
 *
 * - identifyPromisingOpportunities - A function that identifies promising online business opportunities.
 * - IdentifyPromisingOpportunitiesInput - The input type for the identifyPromisingOpportunities function.
 * - IdentifyPromisingOpportunitiesOutput - The return type for the identifyPromisingOpportunities function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyPromisingOpportunitiesInputSchema = z.object({
  marketTrends: z
    .string()
    .describe('Description of current market trends and emerging technologies.'),
  userInterests: z
    .string()
    .describe('Description of the user interests and skills.'),
});
export type IdentifyPromisingOpportunitiesInput =
  z.infer<typeof IdentifyPromisingOpportunitiesInputSchema>;

const OpportunitySchema = z.object({
  opportunityName: z
    .string()
    .describe('Name of the business opportunity.'),
  description: z.string().describe('A short description of the business.'),
  potential: z
    .string()
    .describe('An assessment of the opportunities potential.'),
  risk: z.string().describe('An assessment of the risks involved.'),
  priority: z
    .string()
    .describe(
      'A priority score, from 1-10, of which opportunity to pursue first.'
    ),
});

const IdentifyPromisingOpportunitiesOutputSchema = z.array(
  OpportunitySchema
);
export type IdentifyPromisingOpportunitiesOutput =
  z.infer<typeof IdentifyPromisingOpportunitiesOutputSchema>;

export async function identifyPromisingOpportunities(
  input: IdentifyPromisingOpportunitiesInput
): Promise<IdentifyPromisingOpportunitiesOutput> {
  return identifyPromisingOpportunitiesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyPromisingOpportunitiesPrompt',
  input: {schema: IdentifyPromisingOpportunitiesInputSchema},
  output: {schema: IdentifyPromisingOpportunitiesOutputSchema},
  prompt: `You are an AI assistant designed to identify promising online business opportunities based on market trends and user interests.

Analyze the provided market trends and user interests to pinpoint ventures with high potential, assessing market gaps and emerging trends.

Market Trends: {{{marketTrends}}}
User Interests: {{{userInterests}}}

Consider various online business models, including but not limited to: side-hustles, passive income generators, freelance performance portals, dropshipping e-commerce traders, and social media management.

Return the opportunities as a JSON array.
`,
});

const identifyPromisingOpportunitiesFlow = ai.defineFlow(
  {
    name: 'identifyPromisingOpportunitiesFlow',
    inputSchema: IdentifyPromisingOpportunitiesInputSchema,
    outputSchema: IdentifyPromisingOpportunitiesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
