// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies promising online business opportunities with minimal manual input, assessing market gaps and emerging trends to pinpoint ventures with high potential.
 *
 * - identifyPromisingOpportunities - A function that identifies promising online business opportunities.
 * - IdentifyPromisingOpportunitiesInput - The input type for the identifyPromisingOpportunities function.
 * - IdentifyPromisingOpportunitiesOutput - The return type for the identifyPromisingOpportunities function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyPromisingOpportunitiesInputSchema = z.object({
  marketTrends: z
    .string()
    .describe('Description of current market trends and emerging technologies.')
    .optional(),
  userInterests: z
    .string()
    .describe('Description of the user interests and skills.')
    .optional(),
  context: z.string().optional().describe('Optional context or data provided by the user for analysis.'),
});
export type IdentifyPromisingOpportunitiesInput =
  z.infer<typeof IdentifyPromisingOpportunitiesInputSchema>;

const OpportunitySchema = z.object({
  opportunityName: z
    .string()
    .describe('Name of the business opportunity.'),
  description: z.string().describe('A short description of the business.'),
  potential: z
    .string()
    .describe('An assessment of the opportunities potential, considering financial upside and market size.'),
  risk: z
    .string()
    .describe('An assessment of the risks involved, including market, execution, and financial risks.'),
  quickReturn: z
    .string()
    .describe('An assessment of how quickly a return on investment can be expected (e.g., Short, Medium, Long term).'),
  priority: z
    .string()
    .describe(
      'A priority score, from 1-10, of which opportunity to pursue first. This should be a synthesis of potential, risk, and quick return.'
    ),
});

const IdentifyPromisingOpportunitiesOutputSchema = z.array(
  OpportunitySchema
);
export type IdentifyPromisingOpportunitiesOutput =
  z.infer<typeof IdentifyPromisingOpportunitiesOutputSchema>;

export async function identifyPromisingOpportunities(
  input: IdentifyPromisingOpportunitiesInput
): Promise<IdentifyPromisingOpportunitiesOutput> {
  return identifyPromisingOpportunitiesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyPromisingOpportunitiesPrompt',
  input: {schema: IdentifyPromisingOpportunitiesInputSchema},
  output: {schema: IdentifyPromisingOpportunitiesOutputSchema},
  prompt: `You are an AI assistant designed to identify promising online business opportunities based on a matrix of highest potential, low risk, and quick return. Your goal is to find opportunities that can be launched quickly to go from 'idea to income' in days, not months.

If the user provides context, use that as the primary source for analysis. Otherwise, analyze the provided market trends and user interests to pinpoint ventures with high potential. For each opportunity, evaluate its potential, risk, and the expected time to see a return.

{{#if context}}
User-Provided Context for Analysis (Primary Source):
{{{context}}}
{{/if}}
{{#if marketTrends}}
Market Trends: {{{marketTrends}}}
{{/if}}
{{#if userInterests}}
User Interests: {{{userInterests}}}
{{/if}}

**Framework for "Idea to Income" Opportunity Discovery:**
Your suggestions must be actionable and align with the following rapid-execution prompts. The goal is to create lean, high-impact business models.

1.  **Profit Radar**: Analyze the user's concept and target audience. Identify market gaps, high-potential niches, and key competitors. Focus on customer pain points that can be solved quickly.
2.  **Offer That Prints Money**: Frame the opportunity as a high-value offer. Suggest bonuses, pricing psychology, and value-boosting tactics to make it irresistible.
3.  **Instant Brand-in-a-Box**: For each opportunity, suggest a potential brand name, tagline, and tone of voice. This is about creating a quick, memorable brand identity.
4.  **Website That Sells**: Conceptualize a simple, high-converting website structure. Focus on trust signals and overcoming customer objections.
5.  **7-Day Hype Machine**: Think about how this opportunity could be launched in a week. What pre-launch content, emails, or social media posts would be needed?
6.  **Zero-Ad Sales Plan**: Prioritize opportunities that can get their first customers without a marketing budget. How can a personal network or social media be leveraged?
7.  **Objection Killer**: What are the top 1-2 objections a customer might have? How can the business idea proactively address them?
8.  **Partnership Power Plays**: Suggest 1-2 potential partnership types that could drive traffic and credibility fast.
9.  **60-Day Scale Sprint**: Briefly outline what the first 60 days could look like. What are the key milestones for growth?
10. **Automation Money Machine**: How can this business model be automated early on to spare time for the human stakeholder?

**Business Model Considerations:**
- **SaaS & Service Hybrids**: Look for unmet needs in the SaaS market, especially "pain-killer" solutions for niche problems.
- **Packaged Services**: Offer service-based solutions in clear, productized packages.
- **Subscriptions**: Propose subscription tiers, including free tiers or membership discounts.
- **Lean Launch**: The ideas must be able to be launched and validated quickly. Avoid ideas that require long development cycles or heavy upfront investment. The user stakeholder is "Lazy Larry" and wants to be an observer/approver.

For each opportunity, synthesize these points into a compelling business case. The final priority score should heavily favor high potential, low risk, and **quick return**. If the user has provided context, use that as a primary source of inspiration and analysis.

Return the opportunities as a JSON array.
`,
});

const identifyPromisingOpportunitiesFlow = ai.defineFlow(
  {
    name: 'identifyPromisingOpportunitiesFlow',
    inputSchema: IdentifyPromisingOpportunitiesInputSchema,
    outputSchema: IdentifyPromisingOpportunitiesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
